scrape_configs:
  - job_name: prometheus
    static_configs: # targets to scrape from
     - targets: ['localhost:9090']
  - job_name: metric.api
    scrape_interval: 2s # By default, scrape targets every 15 seconds.
    static_configs:
     - targets: ['metric.api:8080']
  

       